<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.8" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.8" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.16" />
    <PackageReference Include="QuestPDF" Version="2024.10.0" />
    <PackageReference Include="ClosedXML" Version="0.102.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VendaCore.Application\VendaCore.Application.csproj" />
    <ProjectReference Include="..\VendaCore.Domain\VendaCore.Domain.csproj" />
  </ItemGroup>
</Project>
